# Generated by Django 5.2 on 2025-07-11 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('game_creation', models.BigIntegerField()),
                ('game_end_ts', models.BigIntegerField()),
                ('game_duration', models.IntegerField()),
                ('game_mode', models.CharField(max_length=50)),
                ('game_type', models.CharField(max_length=50)),
                ('game_version', models.CharField(max_length=50)),
                ('map_id', models.IntegerField()),
                ('queue_id', models.IntegerField()),
                ('tournament_code', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Death',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.BigIntegerField()),
                ('participant_id', models.IntegerField()),
                ('killer_id', models.IntegerField()),
                ('assisting_participant_ids', models.TextField()),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.match')),
            ],
            options={
                'unique_together': {('match', 'timestamp', 'participant_id')},
            },
        ),
        migrations.CreateModel(
            name='Ban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.IntegerField()),
                ('pick_turn', models.IntegerField()),
                ('champion_id', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.match')),
            ],
            options={
                'unique_together': {('match', 'team_id', 'pick_turn')},
            },
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.IntegerField()),
                ('type', models.CharField(max_length=50)),
                ('first', models.BooleanField()),
                ('kills', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.match')),
            ],
            options={
                'unique_together': {('match', 'team_id', 'type')},
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.IntegerField()),
                ('puuid', models.CharField(max_length=100)),
                ('riot_name', models.CharField(max_length=100)),
                ('team_id', models.IntegerField()),
                ('champion_id', models.IntegerField()),
                ('champion_name', models.CharField(max_length=100)),
                ('individual_position', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('summoner1_id', models.IntegerField()),
                ('summoner2_id', models.IntegerField()),
                ('kills', models.IntegerField()),
                ('deaths', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('total_damage_dealt_champs', models.IntegerField()),
                ('damage_self_mitigated', models.IntegerField()),
                ('total_heal', models.IntegerField()),
                ('total_damage_taken', models.IntegerField()),
                ('largest_killing_spree', models.IntegerField()),
                ('penta_kills', models.IntegerField()),
                ('quadra_kills', models.IntegerField()),
                ('vision_score', models.IntegerField()),
                ('wards_placed', models.IntegerField()),
                ('total_minions_killed', models.IntegerField()),
                ('neutral_minions_killed', models.IntegerField()),
                ('time_ccing_others', models.IntegerField()),
                ('item0', models.IntegerField()),
                ('item1', models.IntegerField()),
                ('item2', models.IntegerField()),
                ('item3', models.IntegerField()),
                ('item4', models.IntegerField()),
                ('item5', models.IntegerField()),
                ('item6', models.IntegerField()),
                ('gold_earned', models.IntegerField()),
                ('gold_spent', models.IntegerField()),
                ('champ_level', models.IntegerField()),
                ('champ_experience', models.IntegerField()),
                ('win', models.BooleanField()),
                ('first_blood_kill', models.BooleanField()),
                ('first_tower_kill', models.BooleanField()),
                ('team_position', models.CharField(max_length=50)),
                ('time_played', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.match')),
            ],
            options={
                'unique_together': {('match', 'participant_id')},
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.IntegerField()),
                ('win', models.BooleanField()),
                ('baron_first', models.BooleanField()),
                ('baron_kills', models.IntegerField()),
                ('dragon_first', models.BooleanField()),
                ('dragon_kills', models.IntegerField()),
                ('tower_first', models.BooleanField()),
                ('tower_kills', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.match')),
            ],
            options={
                'unique_together': {('match', 'team_id')},
            },
        ),
    ]
