# Generated by Django 5.2 on 2025-08-03 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_ban_champion_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='champion',
            new_name='champion_id',
        ),
    ]
