# Generated by Django 5.2 on 2025-08-03 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_champion_participant_champion_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='champion_id',
            new_name='champion',
        ),
    ]
