# Generated by Django 5.2 on 2025-08-03 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_champion_id_participant_champion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ban',
            old_name='champion_id',
            new_name='champion',
        ),
    ]
