# Generated by Django 5.2 on 2025-08-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_champion_id_ban_champion'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='game_region',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
    ]
