# Generated by Django 5.2 on 2025-08-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_backfill_match_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='objet_complet',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
