# Generated by Django 5.2 on 2026-03-23 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_match_objet_complet'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='rank_division',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='participant',
            name='rank_lp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='rank_queue',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='participant',
            name='rank_tier',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
