# Generated by Django 5.2 on 2026-03-25 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_participant_rank_division_participant_rank_lp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='bait_pings',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='champion_transform',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='damage_dealt_to_objectives',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='damage_dealt_to_turrets',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='damage_per_minute',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='danger_pings',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='detector_wards_placed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='game_ended_in_early_surrender',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='game_ended_in_surrender',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='get_back_pings',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='gold_per_minute',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='inhibitor_kills',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='inhibitor_takedowns',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='jungle_cs_before_10_minutes',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='killing_sprees',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='lane',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='participant',
            name='lane_minions_first_10_minutes',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='largest_multi_kill',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='longest_time_spent_living',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='objectives_stolen',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='objectives_stolen_assists',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='perks',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='participant',
            name='ping_stats',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='participant',
            name='primary_rune_selections',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='participant',
            name='primary_rune_style',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='secondary_rune_selections',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='participant',
            name='secondary_rune_style',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='skill_order',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='participant',
            name='solo_kills',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='stat_perks',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='participant',
            name='stealth_wards_placed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='team_early_surrendered',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='total_damage_shielded_on_teammates',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='total_heals_on_teammates',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='total_time_cc_dealt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='turret_kills',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='turrets_lost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='vision_score_advantage_lane_opponent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='vision_wards_bought_in_game',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='wards_killed',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
